{% set name = "cython-fortran-file" %}
{% set version = "0.2.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/cphyc/cython_fortran_file/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 5debbcbdb36013747aeff066eb57c5c7273734fb6f5c1fe6ddeb6746644e99bb

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - cython
    - numpy
  run:
    - python
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - cython_fortran_file

about:
  home: https://github.com/cphyc/cython_fortran_file/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: An efficient package to read fortran-record files in Python

  description: |
    This package is a fast and easy reader for record-based binary format, as written by Fortran.
  doc_url: https://github.com/cphyc/cython_fortran_file
  dev_url: https://github.com/cphyc/cython_fortran_file

extra:
  recipe-maintainers:
    - cphyc
