{% set name = "cython-fortran-file" %}
{% set version = "0.2.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/cphyc/cython_fortran_file/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 73cea2ba4f27edb0d02605e1b742ce6db7ad6a9d222dd2e84283ca46e19e4a04

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - cython
    - numpy
  run:
    - python
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - cython_fortran_file

about:
  home: https://github.com/cphyc/cython_fortran_file/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: An efficient package to read fortran-record files in Python

  description: |
    This package is a fast and easy reader for record-based binary format, as written by Fortran.
  doc_url: https://github.com/cphyc/cython_fortran_file
  dev_url: https://github.com/cphyc/cython_fortran_file

extra:
  recipe-maintainers:
    - cphyc
