travis:
  secure:
    BINSTAR_TOKEN: ccv99aqbqQxKKkL7Fec00RkIUqvtV/aCJEW2MH14K+14ArBI03BD8xkW6xwvnww1uwDQT8RqfNBqiU9bJwX/v9gQzGdHIGR5dgbqsPPpFeVY5817T0vNLAwLEkudW+6BwhkHJgCDXcRSZSg4xg1/Ji6fpNNH/ToiTT0ttalgVFQnWR7WBmMZ9py6zM4/OPXwOirDiGqhWCqwAXLnX7latk8qv8f20i1cL/s4gkHacK+i8keoELlQUq7HfLDz+VVC++ptmsoE9yV9N7MzRHoCMSCxESarwnIHjq8Iv9dssLKLHMJk+EfUZWYI6ebMFOmEkTNNU7nQatWL/K9GT9+/U+2zei7ncJT/Zkrmvz8xhgIzAW6Ugasl/GaCKJPYrExYJcytMwHRNAwhfozf3CiydWkBIpTGAPtfRCiljcOor/5CgRZtRSRCzkG/eH8RGv6zt+Y4yCze0ElNSUHsJRncxbrKT7awNomXy3zQk+O19xxfFB4auicMrGHjYyQidPlfD1I6IDQiC30wF3kASZCP3ENsUXFIl0OsPL6ZVSQjyplV354BKDa/I8HnZe03JDObLAvIn32uydGwd/1DVTXPkxJxsyKjOQMccn9/yQC1VtoD3DDDXQFznevT3D0KKOCXhg5sHgnD4svXtqpgLsFDTJ/yMDJfyfXWKosjO0wOmIk=
conda_forge_output_validation: true
bot:
  automerge: True
